### ISSUE TITLE
Interaction with Shiny bookmarking is broken?

### ISSUE THREAD

**Issue by Lupus** [trafficonese/daterangepicker#3]
I've tried to use bookmarking on my shiny dashboard with daterangepicker, and what I observe is that other inputs get their values from the session (I use url backend), while daterangepicker is initialized to default values.

**Comment by trafficonese** [comment]
Yeah, I never really used bookmarking in my Apps, thats why I just skipped it. 
I will have a look how other inputs manage the bookmarking and state restoring.

**Comment by Lupus** [comment]
Wow, thanks for quick reply! Would be awesome! :+1:

**Comment by trafficonese** [comment]
I just pushed 51e1edc. Could you check if that solves the issue?

**Comment by Lupus** [comment]
Hm, dashboard state depending on daterangepicker is now properly restored, but the daterangepicker UI still shows defaults.

**Comment by trafficonese** [comment]
Could you maybe give a small example?

With this little example, the start & enddate are restored properly.
```
library(shiny)
library(daterangepicker)

ui <- function(request) {
  fluidPage(
  bookmarkButton(),
  dateRangeInput("daterange1", "Date range:",
                 start = "2001-01-01",
                 end   = "2010-12-31"),
  daterangepicker(
    inputId = "daterange",
    label = "Pick a Date",
    start = Sys.Date() - 30, end = Sys.Date(),
    max = Sys.Date(),
    icon = icon("calendar")
  )
)
}

server <- function(input, output, session) {}
enableBookmarking(store = "url")
shinyApp(ui, server)
```

**Comment by Lupus** [comment]
Indeed it works fine with your example. I'll need to dig into my larger dashboard to try to understand what's going on there. Thanks!

**Comment by Lupus** [comment]
Actually I got it working, not sure what was wrong, but it was likely something in my code. Thanks for quick fix!
